/* ExifLens tests: runs the shared engine over the corpus and compares every
   field against tests/expected.json (generated by oracle.py using exifread,
   with independent python GPS-decimal and APEX conversions). */
'use strict';
const fs=require('fs'),path=require('path');
const engine=require(path.join(__dirname,'..','engine.js'));
function load(p){
  if(fs.existsSync(p))return new Uint8Array(fs.readFileSync(p));
  const b=p+'.b64';
  if(fs.existsSync(b))return new Uint8Array(Buffer.from(fs.readFileSync(b,'utf8').trim(),'base64'));
  throw new Error('missing corpus '+p);
}
const items=JSON.parse(fs.readFileSync(path.join(__dirname,'expected.json'),'utf8')).items;
let fail=0,pass=0;
function eq(a,b,label){
  const sa=JSON.stringify(a),sb=JSON.stringify(b);
  if(sa===sb){pass++;return;}
  fail++;console.log('FAIL '+label+': got '+sa+' want '+sb);
}
function approx(a,b,tol,label){
  if(typeof a==='number'&&Math.abs(a-b)<=tol){pass++;return;}
  fail++;console.log('FAIL '+label+': got '+a+' want ~'+b);
}
const SKIP=new Set(['file','has_exif','byte_order','gps_lat_dec','gps_lon_dec','gps_alt_signed','apex_shutter_s','apex_fnumber']);
for(const item of items){
  const bytes=load(path.join(__dirname,'corpus',item.file));
  const r=engine.parse(bytes);
  const T=item.file+' ';
  eq(r.has_exif,item.has_exif,T+'has_exif');
  if(item.byte_order)eq(r.byte_order,item.byte_order,T+'byte_order');
  if(!item.has_exif)continue;
  eq(r.errors.length,0,T+'errors '+JSON.stringify(r.errors));
  for(const k of Object.keys(item)){
    if(SKIP.has(k))continue;
    eq(r.fields[k],item[k],T+k);
  }
  if(item.gps_lat_dec!==undefined)approx(r.fields.GPSLatitudeDec,item.gps_lat_dec,2e-6,T+'gps_lat_dec');
  if(item.gps_lon_dec!==undefined)approx(r.fields.GPSLongitudeDec,item.gps_lon_dec,2e-6,T+'gps_lon_dec');
  if(item.gps_alt_signed!==undefined)approx(r.fields.GPSAltitudeSigned,item.gps_alt_signed,1e-9,T+'gps_alt_signed');
  if(item.apex_shutter_s!==undefined)approx(r.fields.ApexShutterSeconds,item.apex_shutter_s,1e-6,T+'apex_shutter_s');
  if(item.apex_fnumber!==undefined)approx(r.fields.ApexFNumber,item.apex_fnumber,1e-4,T+'apex_fnumber');
}
console.log(pass+' passed, '+fail+' failed');
process.exit(fail?1:0);
